# frozen_string_literal: true

source "https://rubygems.org"

gemspec

gem "puma"
gem "redcarpet"
gem "sprockets-rails"
gem "sqlite3"
gem "yard"
gem "y-rb"

group :development, :test do
  gem "foreman"
  gem "jsbundling-rails"
  gem "redis", "~> 5.0.6"
  gem "rspec"
  gem "rspec-rails"
  gem "rubocop"
  gem "rubocop-performance"
  gem "rubocop-rails"
  gem "rubocop-rspec"
end

# Start debugger with binding.b [https://github.com/ruby/debug]
# gem "debug", ">= 1.0.0"
